### PR TITLE
Redirect for speech-api

### PR DESCRIPTION
**Pull request by marcoscaceres**
Don't merge until: 
https://github.com/w3c/speech-api/issues/67

### CODE REVIEW

**Comment by foolip** [comment]
If the repo is transferred then it will no longer deploy to w3c.github.io will it? In other words, will this really work?

**Comment by foolip** [comment]
Oh, sorry, I didn't see which repo this PR was on, this is fixing the fact transferring the repo would break things :)

The files removed in https://github.com/w3c/speech-api/pulls should also be redirected, or perhaps you'd like to leave them just on w3c.github.io?

**Comment by marcoscaceres** [comment]
> The files removed in https://github.com/w3c/speech-api/pulls should also be redirected, or perhaps you'd like to leave them just on w3c.github.io?

Yeah, that's a great suggestion. Will do that.

**Comment by foolip** [comment]
Will something blow up in an obvious way if in the future the repo is moved out of the WICG and back to a w3c.github.io URL? I just hope that then these extra files won't silently become 404, but it is what I'd guess.

**Comment by marcoscaceres** [comment]
> Will something blow up in an obvious way if in the future the repo is moved out of the WICG and back to a w3c.github.io URL? I just hope that then these extra files won't silently become 404, but it is what I'd guess.

We can cross that bridge when we get to it... not too concerned about the old files blowing up as they will be 5 years old by then. I feel like we should just kill them at the point where we get the spec back here. If someone really wants 5 year old errata (or the outdated spec), they can always dig it out out of git.

**Comment by foolip** [comment]
What I'm getting at is that we won't even notice there is a bridge to cross then, so the decision to break the URLs is effectively now. But I'm OK with that, I don't volunteer to do work to prevent it from happening in the future.

**Comment by marcoscaceres** [comment]
I'm ok to fix links. It's already fairly annoying that search engines are the old finding:
https://w3c.github.io/speech-api/speechapi.html

Instead of the more recent one... so I think that one should at least be redirecting directly. Will fix that now as part of the PR.

**Comment by marcoscaceres** [comment]
Ok, the following now all go to "index.html":

* speech-api/speechapi.html
* speech-api/webspeechapi.html

Errata now says that it's not longer maintained.

**Comment by marcoscaceres** [comment]
This should be good to merge... @sideshowbarker, I think you can actually delete w3c/speech-api. When transferring it's best to not recreate the repos and just do what we do here. That way, GitHub will automatically handle the redirects for issues.

**Comment by foolip** [comment]
Why wasn't w3c/speech-api transferred? Now URLs which I have in my history like https://github.com/w3c/speech-api/pull/63 are 404 instead of redirecting.

**Comment by marcoscaceres** [comment]
Not sure what happened... worst case, we can replay this:

 1. delete the current w3c/speech-api one
 1. move the wicg/speech-api back to w3c.
 1. move w3c/speech-api back to wicg.

That should heal things, I think 🤞

**Comment by foolip** [comment]
Thanks @sideshowbarker! My cool URLs now work again :D

**Pull request merged**
