### PR TITLE
Update meaning of field “shortName” in file “w3c.json” [EDIT: remove it altogether]

### PR DESCRIPTION
**Pull request by tripu**
Fix meaning of field `shortName` in file `w3c.json` (cf w3c/manifest#605).

(Also, commit generated changes that went missing a while ago, in commit 19626dcf446a8a2fafdf552a01dbe442c7492925.)

### CODE REVIEW

**Comment by tripu** [comment]
Okay to remove that field, if Ash-Nazg is not using it for anything.
Do you think that's the case, @dontcallmedom?
https://github.com/w3c/ash-nazg/search?utf8=%E2%9C%93&q=shortName&type=

**Comment by dontcallmedom** [comment]
ash-nazg is populating it by default, but not using it, and I'm not aware of other code making use of it, so let's kill it

**Comment by tripu** [comment]
Okay, @dontcallmedom. Let me update this PR&hellip;

**Comment by tripu** [comment]
Too fast! :) I'm submitting a PR in Ash-Nazg, too.

**Comment by dontcallmedom** [comment]
that will handily address https://github.com/w3c/ash-nazg/issues/95 :)

**Pull request merged**
