### PR TITLE
Added a reference to the W3C id

### PR DESCRIPTION
**Pull request by iherman**
Have added a reference to the W3C Id, in case it is necessary

### CODE REVIEW

**Comment by tripu** [comment]
I think I'm not in favour of this change (or at least, not in favour of this particular syntax). It complicates things a little bit too much IMO. And, when there's just one ID (not a pair), do we assume that's GH, or W3C?

But I don't have a strong opinion.

Whatever the decision, someone please merge or close.
Who's supposed to be taking care of contributions to this repo?
@plehegar, @dontcallmedom&hellip;?

**Comment by plehegar** [comment]
imho, unless we have a use case in mind, we shouldn't do the change.

**Comment by tripu** [comment]
We may have found that use case, after all.

Last week during the Systeam F2F we discussed the need for more metadata to be embedded in GH repos containing specs. [`w3c/ash-nazg`](https://github.com/w3c/ash-nazg) is coming to the rescue, but having more granular data inside `w3c.json` would not hurt. In particular, it may help mapping W3C IDs to GH IDs, like @iherman was suggesting here.

I'll keep this open, and recycle when that requirement is clearer, maybe with a slightly different syntax.

**Comment by dontcallmedom** [comment]
@tripu there is no question that we will need a robust way of linking github and w3c identities — ash-nazg does some of it already, but we need a system where users themselves can do the binding and oauth is used to verify it.
I'm pretty sure that doing the linking in w3c.json is not the right way, and would end up duplicating the data that we will hopefully collect once we have such a system.

**Comment by tripu** [comment]
Closing for now, @iherman.
As @dontcallmedom pointed out, the matching will eventually done by [other tools](https://github.com/w3c/ash-nazg).
For now, let's track GH usernames only in `w3c.json`.

**Pull request closed without merging**
