### PR TITLE
Document the use of milestones and projects.

### PR DESCRIPTION
**Pull request by jyasskin**
Long-lived preview: https://rawgit.com/jyasskin/w3c.github.io/patch-1/issue-metadata.html

### CODE REVIEW

**Comment by tripu** [comment]
Thank you for the idea, @jyasskin. I personally think that labels should not convey time-sensitive information&nbsp;&mdash;&nbsp;*milestones* and *projects* are for that.

The meaning of &ldquo;next version&rdquo; is bound to change as new releases appear. For example, a change may be deemed long-term (thus no label), then planned for an upcoming release (so, &ldquo;next version&rdquo;), but overlooked in that release (so, expected for the current release; no label again), etc. Labels, IMHO, should reflect static attributes of items. I find *projects* are better suited to organise cycles of work.

**Comment by jyasskin** [comment]
That's plausible. Would it make sense to include advice on using projects and milestones in this document? I'd like to be able to point folks to one place to explain how to manage issue metadata in a way that's consistent across web specs.

**Comment by tripu** [comment]
@jyasskin: that (documenting good practices about milestones and projects) makes more sense to me, yes.

I don't know if W3C groups have enough experience yet managing GH milestones and projects as to put that in writing. Especially the latter. I have seen groups using those features, but I'm not sure that a consistent pattern, or a W3C way of doing things, has emerged yet from that usage.

I suspect you know more about this than I do. By all means feel free to draft a section in the FAQ, or something like that. (I suggest you run `npm run build` before submitting your PR, to regenerate the static pages.)

Thank you again for contributing!

**Comment by jyasskin** [comment]
Here's a proposal. I'll try to get some feedback from folks who've edited some more specs.

**Comment by tobie** [comment]
I've used `FPWD`, `level-[num]`, `CR`, `Future Work` etc. as milestones.

I think a really useful thing would be to have matching color coding for the labels across repositories, and a script whoever's creating the repo could invoke to create those by default.

Worthwhile talking with @marcoscaceres about the repo-scaffolding work he's setting up for WICG.

**Comment by tripu** [comment]
@sandhawke also worked on this, suggesting a common set of labels and providing detailed instructions to import that set into a repo: [`sandhawke/spec-labels-min`](https://github.com/sandhawke/spec-labels-min).

It may be worth merging efforts somehow.

**Comment by jyasskin** [comment]
+1 to merge @sandhawke's labels into this repository, specify colors for labels, and include this set in the repo-generation tools. I'd prefer to make progress on the labels in a different PR, after the structure for milestones and projects is set up in this one. I believe colors aren't relevant for milestones?

**Comment by jyasskin** [comment]
@tobie I've added the rest of the REC-process milestones to the sample list, and "future-work" for things that are just vaguely postponed.

**Comment by plehegar** [comment]
LGTM

**Pull request merged**
