### PR TITLE
Modify margin when the screen size is less than 840px

### PR DESCRIPTION
**Pull request by abouthiroppy**
hello:)

I modified margin when the size of screen is less than 800px.

## before
This screen size is iPhone5s size (320x568).

## after
Modified left and right margin.

## check the devices
- chrome
- firefox
- safari
- iPhone6s
- iPhone5s
- nexus5x

### CODE REVIEW

**Comment by abouthiroppy** [comment]
Rebased.

**Comment by tripu** [comment]
Thank you, @abouthiroppy&nbsp;&mdash;&nbsp;this is good.

There's a slightly annoying hiccup around the cut-off width: if you resize the window slowly, you'll notice that when the width of the viewport is slightly above the frontier (eg, 841px) the margins at both sides are actually smaller than 20px. Then when the width is 840px or less, margins are 20px again. That causes a slight bounce when resizing. I think it has to do with vertical scroll bars being counted to compute the overall width.

It's a small thing, but do you think you can fix it?

**Comment by abouthiroppy** [comment]
@tripu Thank you for your reply:)

is my understanding correct?



I think the problem is difficult.

Do you have any ideas?

**Comment by tripu** [comment]
@abouthiroppy, these two screenshots show what I mean:

Width: 841px :point_down:

w3c github io-841px

Width: 840px :point_down:

w3c github io-840px

Right before the media query quicks in (at 841px), margins at both sides are 13px because the scroll bar takes 15px
(841 - 800 - 15) / 2 = 13
But when the width of the window is reduced by 1px, margins are forced to be 20px. So the transition isn't smooth; widths jump at the boundary.

In this particular case (my Chromium on Ubuntu), I think it'd be solved by setting the cut-off width at 854px, because
(855 - 800 - 15) / 2 = 20
&hellip;but I wonder how to solve it for the generic case (we don't know whether there is a vertical scroll bar or not, or how much width it takes; eg, in the Firefox I have at hand, these widths change slightly).

**Comment by abouthiroppy** [comment]
yep, that's what I wanted to say.
This problem depends on OS(e.g. scrollbar of mac is slim but scrollbar of windows is fat) and browser.
umm... I don't have a solution :cry:

**Comment by tripu** [comment]
Perhaps @guibbs has a recipe for this?

**Comment by guibbs** [comment]
I have no quick solution right now. It might take a while to find one. I think this is not a really big issue and we should merge. :)
People will go either on a mobile device or desktop but won't really resize their browser all the time.
You can still open an issue with a low priority.

**Comment by tripu** [comment]
Note to self: [*&ldquo;Detect scrollbar width with JavaScript&rdquo;*](https://davidwalsh.name/detect-scrollbar-width).

**Pull request merged**
