### PR TITLE
Initial revision for labels

### PR DESCRIPTION
**Pull request by plehegar**
This is an attempt to help harmonize GitHub labels between repos

### CODE REVIEW

**Comment by tripu** [comment]
Taking the liberty to merge, since there's no assigned reviewer, at least two of us agree on the changes, and there are no comments against this after a couple of days.

**Comment by plehegar** [comment]
(let's keep this branch for 2 weeks while the HTML editors look at it)

**Comment by tripu** [comment]
Now? :)

**Comment by plehegar** [comment]
thanks for the ping. @LJWatson, did you get feedback from the HTML editors? Is it good enough to spread those labels to spec-prod?

**Pull request merged**
