### PR TITLE
Add optional field “license” to “w3c.json”, and explain SPDX

### PR DESCRIPTION
**Pull request by tripu**

### CODE REVIEW

**Comment by tripu** [comment]
Note to self:
* [filenames `*w3c.json*` in repos of organisation `w3c`](https://github.com/search?utf8=%E2%9C%93&q=filename%3Aw3c.json+user%3Aw3c&type=Code&ref=searchresults) (~65)
* [filenames `*w3c.json*` in *any* repo](https://github.com/search?utf8=%E2%9C%93&q=filename%3Aw3c.json&type=Code&ref=searchresults) (~215)

**Comment by tripu** [comment]
No activity here.
Assigning to the first W3C contributor to this repo in the last couple of months other than me: @ylafon.

**Comment by tripu** [comment]
Yes, I intend to submit our new licence to SPDX (cf. w3c/hanuman#3).

If our licence is in fact made up of other licences (is that so?), then it's just a matter of submitting that combined licence to SPDX, no?

Anyway, in the meantime adding the optional field to `w3c.json` and explaining its meaning would be good I think. Also, not all software and specs use that license; those projects published under MIT, GPL, CC, etc can start using the field now.

**Comment by plehegar** [comment]
My concern here is that the info on the info is already in LICENSE.md for our specs repo. Adding a field in w3c.json would duplicate the info.

**Comment by tripu** [comment]
@plehegar, isn't that the case with some of the other fields, too? Contacts and shortname one can usually find on the spec(s) too. I think the goal of `w3c.json` is to have that basic info in a machine-readable format. In the future, tools handling all these tools and specs might benefit from knowing what licences they're using.

**Comment by plehegar** [comment]
contact isn't since specs don't list team contacts.
shortname isn't necessarily findable either since specs can use different editing formats and the generated /TR-ready html may not be in the repo.

**Comment by plehegar** [comment]
for tooling purposes, the should start looking at LICENSE.md and, if not there, see w3c.json or package.json?

**Comment by plehegar** [comment]
ALso, keep in mind that http://w3c.github.io/ should be primarly oriented towards using GitHub for specification purposes. Tooling is only secondary. We should make the picture on the start page by talking about Node.js.

**Comment by johanneswilm** [comment]
The point of this particular repo is -- in my understanding -- to allow for redirects on github.io when one changes the name of one of the w3c repositories. Are you guys using this for something else now?

**Comment by tripu** [comment]
I'm closing this PR as it seems I'm the only one who sees the utility of having machine-readable info about the licence (in general; be it specs or any other kind of W3C project).

@johanneswilm: I think this repo has evolved into what you can see at [`w3c.github.io`](https://w3c.github.io/).

**Comment by wseltzer** [comment]
@tripu, the W3C Software and Document license will be included in the 2.6 SPDX release

**Comment by tripu** [comment]
@wseltzer: [`spdx.org/licenses/W3C-20150513.html`](https://spdx.org/licenses/W3C-20150513.html)?

**Pull request closed without merging**
